### ISSUE TITLE
Info zum Datensatz

### ISSUE THREAD

**Issue by Khaireddine-HK** [mariia-h/3._Teilleistung_Gruppenarbeit#2]
Hallo an allen, 
das Skript von der Erstellung des Datensatzes ist schon bereit. Moez sollte der Datensatz in einer csv-Datei bald hochladen. 
Bitte achtet ihr darauf, wie wir die verschiedenen Variablen in unseren Dataframe genannt haben, damit ihr die Variablen eurer Funktonen richtig wählt. 
Danke Leute

**Comment by dalymoez** [comment]
ich habe es schon hochgeladen
