### ISSUE TITLE
Kommentare in Skript_1

### ISSUE THREAD

**Issue by dalymoez** [mariia-h/3._Teilleistung_Gruppenarbeit#3]
Mariie du hast eine sehr gute Dokumentation am anfag des Skripts geschrieben aber es wäre sehr hilfreich sein, wenn du noch ein paar Kommentare  für die verschiedene bearbeitungen in deiner Funktion schreibest. 
Danke <3

**Comment by mariia-h** [comment]
Moez, danke für Hinweis, ich werde das heute aktuelisieren

**Comment by dalymoez** [comment]
perfekt
