### ISSUE TITLE
hier scheint ein Fehler vorzuliegen :Funktion "expect" konnte nicht gefunden werden

### ISSUE THREAD

**Issue by Ayoubhbz** [mariia-h/3._Teilleistung_Gruppenarbeit#5]
https://github.com/mariia-h/3._Teilleistung_Gruppenarbeit/blob/e9da1a697f8ece0834af64a9ec178f308697fb9c/Skript-1.R#L30

**Comment by mariia-h** [comment]
Es liegt in Skript-2 als Hilfsfunktion
