### ISSUE TITLE
gibt nicht das Modus zurück

### ISSUE THREAD

**Issue by Ayoubhbz** [mariia-h/3._Teilleistung_Gruppenarbeit#6]
https://github.com/mariia-h/3._Teilleistung_Gruppenarbeit/blob/c69c582bc19d88ff3005282e5f093bfe7aedcc0e/Skript-1.R#L18

ich glaube ,dass das Falsch ist ,da "which.max "Gibt die Position des Elements mit dem Maximalwert in einem Vektor zurück, und nicht das Modus.

Mein Meinung nach kann man hier auch das Hilf Funktion "getmode" in "Skript-2.R" benutzen. Was haltet ihr davon?

https://github.com/mariia-h/3._Teilleistung_Gruppenarbeit/blob/c69c582bc19d88ff3005282e5f093bfe7aedcc0e/Skript-2.R#L7

**Comment by mariia-h** [comment]
Ich stimme zu

**Comment by mariia-h** [comment]
Ich habe diesen Fehler korrigiert
