### ISSUE TITLE
Diskussion

### ISSUE THREAD

**Issue by mariia-h** [mariia-h/3._Teilleistung_Gruppenarbeit#7]
Nach der Analyse vom simulierte Datensatz sieht man, dass Personen im Durchschnitt 25 Jahre alt sind. Das sehen wir auch aus Kategorisierung der Daten, die Mehrheit sind mittelalt. Außerdem sehen wir, dass alle Befragte in durchschnitt Interesse an Mathematik haben, es würde wir Modalwert = 5, für Variable Interesse_an_Mathematik gezeigt.
Laut berechnete Koeffizienten sieht man dass es fast keine Zusammenhang zwischen Studienfach und Tatsache, dass Person Mathe LK gemacht hat. Das sehen wir dann in Mosaik Plot, die Anteile von denen, die Mathe LK hatten und nicht hatten unterscheiden sich nicht riesig.
Zwischen Interesse an Mathematik und Studienfach sehen wir schon mittlere Zusammenhand. Laut Mosaikplot bei Data Science uns Statistik uns Mathe haben Leute mehr Interesse an Mathematik, bei Informatik dagegen interessieren Leute weniger an Mathematik.  Das gleiche kann man über Zusammenhang zwischen Interesse an Programmieren und Studienfach sagen.
Weiter kann man sagen, dass es keine Korrelation zwischen Interesse am Mathematik und Programmieren besteht. Noch dazu besteht es keine Korrelation zwischen Alter und Tatsache, dass Person Mathe LK hatte.

**Comment by dalymoez** [comment]
Was du gefunden hast ist sehr interessant. Es wäre besser, wenn ich auf die anderen warte bis sie auch ihre Ergebnis und Beobachtungen mitteilen sodass ich sie nicht beeinflüsse. Aber nichtsdestotrotz muss ich dir zusagen, dass ich wegen deinem scharfen Auge beeindruckt bin. (Z.b du hast dich bemerkt, dass wenn es um Mathe LK geht, ist es egal welches Studienfach man studiert ). Kannst du auch deine Plots  in einem PDF Datei oder einfache Photos Datei im  GitHub hochlanden ?

**Comment by Ayoubhbz** [comment]
zu dem, was "mariia-h" gesagt hat, kann man Hier auch ergänzen ,dass das am häufigsten vorkommenden Studienfach "Statistik" ist. Und die Mehrheit der Studierenden, die Mathematik bzw. Informatik studieren, zeigt ein hohes Interesse an Mathematik bzw. Informatik. Und keiner zeigt geringes Interesse an dem jeweiligen Thema.

**Comment by Khaireddine-HK** [comment]
Nach euren sinnvollen Analysen würde ich keine Bemerkung bezüglich der resultierenden Grafiken ergänzen. Ich würde aber vorschlagen, die Intersse an allen Fächern sowohl vor dem Anfang mit dem Studium (also in der Schule) als in der Uni auch zu beobachten, damit wir feststellen können, warum die Fächer beliebt oder unbeliebt sind. Außerdem wäre es sinnvoll die Leistungspunkte oder die Note im Bezug auf die einzelnen Hauptfächern eines Fachstudienganges zu beobachten, weil solche Beobachtung die Interessen spiegeln können und gleichzeitig begründen, warum die Studierenden solche Wahl getroffen haben. Dies könnte eine große Rolle spielen.
